on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: build

jobs:
  phpunit:
    uses: php-forge/actions/.github/workflows/codeception.yml@main
    with:
      codeception-command: |
        ./tests/bin/yii migrate/up --migrationPath=@yii-user/migration --interactive=0
        vendor/bin/codecept run --coverage-xml
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.1', '8.2', '8.3']
